name: Deploy Zola to GitHub Pages

on:
  push:
    branches: [main] 

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clona el repo
        uses: actions/checkout@v3

      - name: Instala Zola
        run: |
          curl -s https://www.getzola.org/install.sh | bash

      - name: Construye el sitio
        run: zola build

      - name: Publica en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
